version: '3.8'
services:
  postgres-db:
    image: postgres:14.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_DB=Blog
      - PGPORT=6543
    ports:
      - '6543:6543'
    volumes: 
      - db:/var/lib/postgresql/data
  api:
    container_name: applifting-blog
    build: .
    image: applifting-blog
    depends_on:
      - postgres-db
    ports:
      - 3000:3000
    environment:
      DB_HOST: postgres-db
      DB_PORT: 6543
    links:
      - postgres-db
    volumes:
      - ./:/src
      - /src/node_modules
volumes:
  db:
    driver: local

